#!/usr/bin/bash
PROJECT_ROOT=../..
VERSION_CONFIG=${PROJECT_ROOT}/VERSION
VERSION_LINE_BASIS='const version string = "OLD_VERSION"'

NEW_VERSION=$(cat ${VERSION_CONFIG})
VERSION_LINE_PATTERN=$(echo ${VERSION_LINE_BASIS} | sed -e "s/OLD_VERSION/.*/") 
NEW_VERSION_STRING=$(echo ${VERSION_LINE_BASIS} | sed -e "s/OLD_VERSION/${NEW_VERSION}/")

OLD_FILE_CONTENTS=$(cat $1)
NEW_FILE_CONTENTS=$(echo "${OLD_FILE_CONTENTS}" | sed -e "s/${VERSION_LINE_PATTERN}/${NEW_VERSION_STRING}/g")
echo "$NEW_FILE_CONTENTS" > $1
